apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: bitnami/wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: "<rds-instance-endpoint>"
            - name: WORDPRESS_DB_USER
              value: "admin"
            - name: WORDPRESS_DB_PASSWORD
              value: "Admin123!"
            - name: WORDPRESS_DB_NAME
              value: "wordpressdb"
